"""
FactInvoiceDetails Table Definition
Stores detailed invoice transaction data
Updated from PostgreSQL schema with 300+ columns in snake_case for StarRocks
"""

TABLE = {
    "order": 7,
    "name": "fact_invoice_details",
    "schema": """CREATE TABLE fact_invoice_details (
                active_flag VARCHAR(1),
                actual_invoiced_quantity DECIMAL(12, 2),
                base_transfer_flag VARCHAR(1),
                base_transfer_percentage DECIMAL(5, 2),
                base_uom VARCHAR(8),
                billing_date INTEGER,
                billing_quantity_in_stock_keeping_unit DECIMAL(12, 2),
                bopp_color VARCHAR(15),
                business_area_code SMALLINT,
                cancelled_invoice_reference_number BIGINT,
                cgst DECIMAL(12, 2),
                claim_no VARCHAR(50),
                cn_value DECIMAL(10, 2),
                cn_value_fc DECIMAL(10, 2),
                company_code SMALLINT,
                created_date INTEGER,
                credit_quantity DECIMAL(10, 2),
                credit_value DECIMAL(10, 2),
                customer_code INTEGER,
                customer_code_org INTEGER,
                defect_code VARCHAR(5),
                department_code_history DECIMAL(8, 4),
                department_code_org INTEGER,
                discount_value DECIMAL(12, 2),
                discount_value_fc DECIMAL(12, 2),
                distribution_channel_code SMALLINT,
                division_code SMALLINT,
                doc_currency VARCHAR(5),
                document_date INTEGER,
                document_type_code VARCHAR(5),
                exchange_rate DECIMAL(5, 2),
                final_approval_date INTEGER,
                frd_date INTEGER,
                freight_charges DECIMAL(12, 2),
                gl_ac_code DECIMAL(12, 2),
                grade_code VARCHAR(10),
                gross_value DECIMAL(12, 3),
                gross_value_fc DECIMAL(12, 3),
                header_text VARCHAR(10),
                igst DECIMAL(12, 2),
                invoice_listing_no VARCHAR(10),
                invoice_no VARCHAR(15),
                invoice_type VARCHAR(6),
                invoice_type_description VARCHAR(40),
                item_number DECIMAL(8, 2),
                ja1x DECIMAL(10, 2),
                jcep DECIMAL(10, 2),
                jexp DECIMAL(10, 2),
                jtc1 DECIMAL(10, 2),
                lr_date INTEGER,
                lr_number VARCHAR(20),
                manufacturing_plant_code SMALLINT,
                material_code VARCHAR(20),
                material_code_org VARCHAR(10),
                material_division SMALLINT,
                mfg_date INTEGER,
                mis_type VARCHAR(5),
                net_date INTEGER,
                net_value DECIMAL(10, 2),
                net_value_fc DECIMAL(10, 2),
                net_weight DECIMAL(15, 2),
                net_weight_in_kg DECIMAL(15, 2),
                order_line_no SMALLINT,
                order_no VARCHAR(20),
                plant_code SMALLINT,
                plant_code_history VARCHAR(10),
                posting_date INTEGER,
                posting_date_df VARCHAR(12),
                price DECIMAL(20, 2),
                product_code VARCHAR(10),
                quantity_in_each DECIMAL(10, 2),
                rate DECIMAL(10, 2),
                reason_code VARCHAR(20),
                reporting_unit DECIMAL(10, 2),
                revised_net_value_msgvg DECIMAL(12, 3),
                revised_net_value_mvg DECIMAL(15, 3),
                rlt_day SMALLINT,
                sales_group_code SMALLINT,
                sales_org_code SMALLINT,
                sales_transfer_cr_no VARCHAR(15),
                sales_transfer_updated_date INTEGER,
                sales_unit VARCHAR(5),
                sales_value DECIMAL(14, 2),
                sgst DECIMAL(10, 2),
                ship_to_party DECIMAL(10, 2),
                storage_location VARCHAR(6),
                sub_defect_code VARCHAR(6),
                sub_reason_code VARCHAR(20),
                total_discount DECIMAL(10, 2),
                total_invoice_value DECIMAL(20, 2),
                total_tax DECIMAL(20, 2),
                transporter_name_1 VARCHAR(20),
                transporter_name_2 VARCHAR(20),
                truck_number VARCHAR(20),
                ugst DECIMAL(10, 2),
                uom VARCHAR(4),
                updated_date INTEGER,
                value_for_cash_discount DECIMAL(20, 2),
                volume_in_kg DECIMAL(10, 2),
                volume_in_ltr DECIMAL(10, 2),
                weight_unit VARCHAR(4),
                za1x DECIMAL(10, 2),
                zabt DECIMAL(10, 2),
                zapd DECIMAL(10, 2),
                zasp DECIMAL(10, 2),
                zavt DECIMAL(10, 2),
                zav1 DECIMAL(10, 2),
                zav2 DECIMAL(10, 2),
                zavi DECIMAL(10, 2),
                zatx DECIMAL(10, 2),
                zafd DECIMAL(10, 2),
                zbvt DECIMAL(10, 2),
                zcdt DECIMAL(10, 2),
                zcep DECIMAL(10, 2),
                zcga DECIMAL(10, 2),
                zcmd DECIMAL(10, 2),
                zcom DECIMAL(10, 2),
                zcr1 DECIMAL(10, 2),
                zcs1 DECIMAL(10, 2),
                zcsr DECIMAL(10, 2),
                zcst DECIMAL(10, 2),
                zctr DECIMAL(10, 2),
                zd51 DECIMAL(10, 2),
                zd52 DECIMAL(10, 2),
                zd53 DECIMAL(10, 2),
                zd54 DECIMAL(10, 2),
                zd55 DECIMAL(10, 2),
                zd56 DECIMAL(10, 2),
                zd57 DECIMAL(10, 2),
                zd58 DECIMAL(10, 2),
                zdad DECIMAL(10, 2),
                zdb1 DECIMAL(10, 2),
                zdb2 DECIMAL(10, 2),
                zdbc DECIMAL(10, 2),
                zdbk DECIMAL(10, 2),
                zddf DECIMAL(10, 2),
                zdis DECIMAL(10, 2),
                zdma DECIMAL(10, 2),
                zebs DECIMAL(10, 2),
                zepd DECIMAL(10, 2),
                zexp DECIMAL(10, 2),
                zfcg DECIMAL(10, 2),
                zfds DECIMAL(10, 2),
                zfm1 DECIMAL(10, 2),
                zfms DECIMAL(10, 2),
                zfp1 DECIMAL(10, 2),
                zfps DECIMAL(10, 2),
                zfrl DECIMAL(10, 2),
                zfrt DECIMAL(10, 2),
                zfru DECIMAL(10, 2),
                zg01 DECIMAL(10, 2),
                ziff DECIMAL(10, 2),
                zifr DECIMAL(10, 2),
                zlpd DECIMAL(10, 2),
                zm01 DECIMAL(10, 2),
                zmrp DECIMAL(10, 2),
                znet DECIMAL(10, 2),
                zoc1 DECIMAL(10, 2),
                zocd DECIMAL(10, 2),
                zocs DECIMAL(10, 2),
                zoct DECIMAL(10, 2),
                zopd DECIMAL(10, 2),
                zope DECIMAL(10, 2),
                zosd DECIMAL(10, 2),
                zotd DECIMAL(10, 2),
                zpcp DECIMAL(10, 2),
                zpdp DECIMAL(10, 2),
                zped DECIMAL(10, 2),
                zpjp DECIMAL(10, 2),
                zprs DECIMAL(10, 2),
                zptr DECIMAL(10, 2),
                zrdi DECIMAL(10, 2),
                zsam DECIMAL(10, 2),
                zscp DECIMAL(10, 2),
                zsev DECIMAL(10, 2),
                zsfp DECIMAL(10, 2),
                zsh1 DECIMAL(10, 2),
                zshs DECIMAL(10, 2),
                zspe DECIMAL(10, 2),
                zspd DECIMAL(10, 2),
                zspp DECIMAL(10, 2),
                zsss DECIMAL(10, 2),
                zsu1 DECIMAL(10, 2),
                zsu2 DECIMAL(10, 2),
                zsur DECIMAL(10, 2),
                ztod DECIMAL(10, 2),
                ztrd DECIMAL(10, 2),
                ztrp DECIMAL(10, 2),
                zupd DECIMAL(10, 2),
                zva1 DECIMAL(10, 2),
                zvat DECIMAL(10, 2),
                zvfr DECIMAL(10, 2),
                zvsi DECIMAL(10, 2),
                zvtr DECIMAL(10, 2),
                zvud DECIMAL(10, 2)
            )
            DISTRIBUTED BY HASH(customer_code, material_code) BUCKETS 20
            PROPERTIES (
                "replication_num" = "1"
            );""",
    "comments": {
        "table": "Stores detailed invoice transaction data.",
        "columns": {},
    },
    "indexes": {},
}
