"""
DimHierarchy Table Definition
Stores the hierarchy data
"""

TABLE = {
    "order": 4,
    "name": "DimHierarchy",
    "schema": """CREATE TABLE DimHierarchy (
                ClusterCode VARCHAR(20),
                ClusterCostCenter BIGINT,
                ClusterDescription VARCHAR(125),
                ClusterEmpCode VARCHAR(100),
                ClusterEmpName VARCHAR(132),
                ClusterEmpPosition VARCHAR(136),
                ClusterMobile BIGINT,
                ClusterPosition INTEGER,
                CreatedDate INTEGER,
                DivisionCode SMALLINT,
                HS VARCHAR(100),
                MDI01A VARCHAR(100),
                MDI01B VARCHAR(100),
                MDI01C VARCHAR(100),
                MDI01D VARCHAR(107),
                PrimaryKey VARCHAR(131),
                PrimaryKeyValue VARCHAR(157),
                ProductCode VARCHAR(112),
                ProductName VARCHAR(143),
                SalesGroup SMALLINT,
                SH2Code VARCHAR(107),
                SH2CostCenterCode VARCHAR(107),
                SH2Email VARCHAR(136),
                SH2EmpCode VARCHAR(100),
                SH2EmpName VARCHAR(136),
                SH2EmpPosition INTEGER,
                SH2HQ VARCHAR(124),
                SH2Mobile VARCHAR(110),
                SH2Name VARCHAR(140),
                SH3Code VARCHAR(107),
                SH3CostCenterCode BIGINT,
                SH3Email VARCHAR(136),
                SH3EmpCode VARCHAR(100),
                SH3EmpName VARCHAR(135),
                SH3EmpPosition INTEGER,
                SH3HQ VARCHAR(128),
                SH3Mobile BIGINT,
                SH3Name VARCHAR(134),
                SH4Code VARCHAR(107),
                SH4CostCenterCode BIGINT,
                SH4Email VARCHAR(133),
                SH4EmpCode VARCHAR(100),
                SH4EmpName VARCHAR(130),
                SH4EmpPosition INTEGER,
                SH4HQ VARCHAR(128),
                SH4Mobile BIGINT,
                SH4Name VARCHAR(134),
                SH5Code VARCHAR(107),
                SH5CostCenterCode BIGINT,
                SH5Email VARCHAR(132),
                SH5EmpCode VARCHAR(100),
                SH5EmpName VARCHAR(130),
                SH5EmpPosition INTEGER,
                SH5HQ VARCHAR(128),
                SH5Mobile BIGINT,
                SH5Name VARCHAR(130),
                SH6Code VARCHAR(107),
                SH6CostCenterCode BIGINT,
                SH6Email VARCHAR(132),
                SH6EmpCode VARCHAR(100),
                SH6EmpName VARCHAR(124),
                SH6EmpPosition INTEGER,
                SH6HQ VARCHAR(121),
                SH6Mobile BIGINT,
                SH6Name VARCHAR(127),
                SH7Code VARCHAR(107),
                SH7CostCenterCode BIGINT,
                SH7Email VARCHAR(130),
                SH7EmpCode VARCHAR(100),
                SH7EmpName VARCHAR(118),
                SH7EmpPosition INTEGER,
                SH7HQ VARCHAR(121),
                SH7Mobile BIGINT,
                SH7Name VARCHAR(122),
                TxnType VARCHAR(145),
                WSSTerritoryCode VARCHAR(107),
                WSSTerritoryName VARCHAR(130)
            )
            DISTRIBUTED BY HASH(ClusterCode) BUCKETS 10
            PROPERTIES (
                "replication_num" = "1"
            );""",
    "comments": {
        "table": "Stores the hierarchy data.",
        "columns": {},
    },
}
