"""
DimMaterial Table Definition
Stores the material data
"""

TABLE = {
    "order": 6,
    "name": "DimMaterial",
    "indexes": {},
    "schema": """CREATE TABLE DimMaterial (
                ActiveFlag VARCHAR(104),
                AverageRateCase DOUBLE,
                AverageRateEach DOUBLE,
                AverageRateKg DOUBLE,
                AverageRateLitre DOUBLE,
                BaseUOM VARCHAR(103),
                BaseUOMDescription VARCHAR(100),
                Category1 VARCHAR(104),
                Category2 VARCHAR(104),
                CATI_II VARCHAR(102),
                CGST_Percent DOUBLE,
                CrossPlantMaterialStatus VARCHAR(102),
                CrossSellingIndicator VARCHAR(101),
                CurrentDWKey VARCHAR(100),
                DefaultRetailFlag SMALLINT,
                DivisionCode SMALLINT,
                DivisionDescription VARCHAR(120),
                DocumentType VARCHAR(103),
                DWKeyProduct VARCHAR(100),
                EIChairmanClubFlag VARCHAR(101),
                FSNCategory VARCHAR(101),
                FSNDescription VARCHAR(121),
                GrossWeight DOUBLE,
                HSNCode DOUBLE,
                HSNDescription VARCHAR(120),
                IGST_Percent DOUBLE,
                MaterialCode VARCHAR(118),
                MaterialDescription VARCHAR(140),
                MaterialGroup VARCHAR(107),
                MaterialGroup1 SMALLINT,
                MaterialGroup1Description VARCHAR(120),
                MaterialGroup2 SMALLINT,
                MaterialGroup2Description VARCHAR(120),
                MaterialGroupDescription VARCHAR(120),
                MaterialType VARCHAR(104),
                MaterialTypeDescription VARCHAR(125),
                MaterialValidFrom INTEGER,
                MaterialValidTo INTEGER,
                MaximumRetailPrice DOUBLE,
                MotherCode VARCHAR(118),
                MotherCodeDescription VARCHAR(140),
                MotherMaterialAverageRateCase DOUBLE,
                MotherMaterialAverageRateEach DOUBLE,
                MotherMaterialAverageRateKg DOUBLE,
                MotherMaterialAverageRateLitre DOUBLE,
                MRPRelevent VARCHAR(101),
                MRPUOM VARCHAR(103),
                NetWeight DOUBLE,
                NewHSNCode VARCHAR(109),
                OldMaterialNumber VARCHAR(118),
                P2PIndicator VARCHAR(101),
                PrdGroup1 VARCHAR(102),
                PrdGroup2 VARCHAR(104),
                PrdGroup3 VARCHAR(108),
                PrdGroup4 VARCHAR(112),
                PrdGroup5 VARCHAR(117),
                PrdGroupSecurity VARCHAR(147),
                PriceToRetailer DOUBLE,
                PriceValidFrom INTEGER,
                PriceValidTo INTEGER,
                ProductGroup1Description VARCHAR(140),
                ProductGroup2Description VARCHAR(140),
                ProductGroup3Description VARCHAR(140),
                ProductGroup4Description VARCHAR(140),
                ProductGroup5Description VARCHAR(131),
                ProductGroup6Description VARCHAR(122),
                ProductGroupDescriptionSecurity VARCHAR(254),
                PTRUOM VARCHAR(103),
                ReasonCode SMALLINT,
                ReasonText VARCHAR(119),
                RecordValidFrom INTEGER,
                RecordValidTo VARCHAR(100),
                ReportingUnit VARCHAR(103),
                RevisedShelfLife SMALLINT,
                SalesForecasting VARCHAR(101),
                SalesGroupCode SMALLINT,
                SalesOrganizationCode SMALLINT,
                SalesUnit VARCHAR(103),
                SalesUnitDescription VARCHAR(109),
                SellingPrice DOUBLE,
                SGST_Percent DOUBLE,
                ShortText VARCHAR(125),
                Size_Dimensions VARCHAR(131),
                SPUOM VARCHAR(103),
                StatusDescription VARCHAR(125),
                TotalShelfLifeDays SMALLINT,
                UGST_Percent DOUBLE,
                Volume DOUBLE,
                VolumeUnit VARCHAR(103),
                WeightUnit VARCHAR(103)
            )
            DISTRIBUTED BY HASH(MaterialCode) BUCKETS 10
            PROPERTIES (
                "replication_num" = "1"
            );""",
    "comments": {
        "table": "Stores the material data.",
        "columns": {},
    },
}
