"""
FactInvoiceSecondary Table Definition
Stores secondary invoice transaction data
"""

TABLE = {
    "order": 8,
    "name": "FactInvoiceSecondary",
    "schema": """CREATE TABLE FactInvoiceSecondary (
                ActiveFlag SMALLINT,
                InvoiceDate INTEGER,
                CustomerCode INTEGER,
                CashDiscount DOUBLE,
                CGSTAmount DOUBLE,
                CGSTPercentage DOUBLE,
                CreatedBySource VARCHAR(355),
                CreatedDate INTEGER,
                CreationDateSource INTEGER,
                CustomerCodeOriginal INTEGER,
                UpdatedBySource VARCHAR(20),
                UpdationDateSource INTEGER,
                Value DOUBLE,
                VATAmount DOUBLE,
                VATPercentage DOUBLE,
                Volume DOUBLE,
                VolumeInKg DOUBLE,
                VolumeInLtr DOUBLE,
                YearMonth INTEGER,
                DateTime DATETIME,
                DamageQuantity DOUBLE,
                DARPANShipToCode VARCHAR(500),
                DealerCode VARCHAR(500),
                DealerCodeDP VARCHAR(180),
                DealerSGKey VARCHAR(150),
                DeletedFlag SMALLINT,
                DiscountAmount DOUBLE,
                DivisionCode SMALLINT,
                FOCQuantity DOUBLE,
                FreightAmount DOUBLE,
                IGSTAmount DOUBLE,
                IGSTPercentage DOUBLE,
                InvoiceDateDF VARCHAR(150),
                InvoiceNo VARCHAR(150),
                InvoicePrintNumber VARCHAR(160),
                ItemCode VARCHAR(200),
                ItemDeterminationCode VARCHAR(120),
                ItemWeight DOUBLE,
                LoadFlag VARCHAR(150),
                MfgListNo VARCHAR(150),
                MISType VARCHAR(150),
                MRP DOUBLE,
                NetWeightInKg DOUBLE,
                OrderNo VARCHAR(200),
                PrintDate VARCHAR(150),
                PrinterName VARCHAR(200),
                Rate DOUBLE,
                ReceivableDate INTEGER,
                RecordType VARCHAR(150),
                ReportingUnit DOUBLE,
                ReportingUnitInEach DOUBLE,
                ReportingValue DOUBLE,
                RevisedNetValueMSGVG DOUBLE,
                RevisedNetValueMVG DOUBLE,
                RouteCode VARCHAR(150),
                RouteName VARCHAR(200),
                SalesGroupCode SMALLINT,
                SchemeAmount DOUBLE,
                SGSTAmount DOUBLE,
                SGSTPercentage DOUBLE,
                StarDiscount DOUBLE,
                StockRequiredQuantity DOUBLE,
                TCSPer DOUBLE,
                TCSVal DOUBLE,
                TransferDate INTEGER,
                TSICode VARCHAR(150),
                TSIName VARCHAR(200),
                Type VARCHAR(355)
            )
            DISTRIBUTED BY HASH(CustomerCode) BUCKETS 20
            PROPERTIES (
                "replication_num" = "1"
            );""",
    "comments": {
        "table": "Stores secondary invoice transaction data.",
        "columns": {},
    },
    "indexes": {},
}
